replicas: 1

resources:
  enabled: true
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    cpu: "250m"
    memory: "250Mi"

rollingUpdate:
  enabled: true
  maxSurge: 50%
  maxUnavailable: 0

readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 5

livenessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 10

service:
  type: "NodePort"
  port: 30007

volumes:
- name: nginx-config
  configMap:
    name: nginx-config

volumeMounts:
- mountPath: /etc/nginx/conf.d/default.conf
  name:  nginx-config
  subPath: default.conf