apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
  {{- include "nginx.labels" . | nindent 4 }}  
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
    {{- include "selector" . | nindent 6 }}  
  {{- if .Values.rollingUpdate.enabled }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "nginx.labels" . | nindent 8 }}  
    spec:
      containers:
      - image: "{{ .Values.image.imageName }}:{{ .Values.image.tag }}"
        name: {{ .Release.Name }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.ports.enabled }}
        ports:
          - containerPort: {{ .Values.ports.containerPort }}
        {{- end }}
        {{- if .Values.volumeMounts }}
        volumeMounts:
          {{- toYaml .Values.volumeMounts | nindent 10}}
        {{- end }}
        {{- if .Values.resources.enabled }}
        resources:
          limits:
            cpu: "{{ .Values.resources.limits.cpu }}"
            memory: "{{ .Values.resources.limits.memory }}"
          requests:
            cpu: "{{ .Values.resources.requests.cpu }}"
            memory: "{{ .Values.resources.requests.memory }}"
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
            tcpSocket:
              port: {{ .Values.ports.containerPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds | default 1 }}
        {{- end }}
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.ports.containerPort }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds}}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds | default 1 }}
        {{- end }}
      {{- if .Values.volumes }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8}}
      {{- end }}
